---
title: "KF_Heifers_Preg"
format: html
editor: visual
---

```{r}
#| echo: false

pacman::p_load(
  readxl,        #read excel files
  readr,         #read csv files
  openxlsx,      #opens worksheets
  rio,           # import/export
  here,          # filepaths
  janitor,       # tables
  tidyverse,     # data mgmt and viz
  zoo,           # dates
  lubridate,     #parse dates
  #broom,         # model output
  #scales,        # for tables %
  gt,              # create tables
  #gtsummmary,   #tables
  #rstatix,
  #meantables,
  knitr,         # tables
  #epiR,          # Sens/Spec
  skimr,          # quick summaries     
  writexl, 
  ggpubr         #insert tables to ggplot
)

```

```{r}
#| label: load data
#| include: false

num_preg <- read_csv("Pen_105_preg.csv", col_types = cols(.default = ("c"))) |>
    mutate(id   = as.numeric(ID),
           due  = lubridate::mdy(DUE),
           dcc  = as.numeric(DCC)) |>
    filter(!is.na(id)) |>
    select(id:dcc)

View(num_preg)
```

```{r}
#| label: Create month fresh
#| include: false

start_date <- min(num_preg$due, na.rm = TRUE)
last_date <- max(num_preg$due, na.rm = TRUE)

freshbymonth <- num_preg |>
                mutate(monfrsh = case_when(
                            due  >=  lubridate::ymd("2024-10-01") & due <=           lubridate::ymd("2024-10-31") ~ "Oct 24",
                            due  >=  lubridate::ymd("2024-11-01") & due <=           lubridate::ymd("2024-11-30") ~ "Nov 24",
                            due  >=  lubridate::ymd("2024-12-01") & due <=           lubridate::ymd("2024-12-31") ~ "Dec 24",
                            due  >=  lubridate::ymd("2025-1-01") & due <=           lubridate::ymd("2025-1-31") ~ "Jan 25",
                            due  >=  lubridate::ymd("2025-2-01") & due <=           lubridate::ymd("2025-2-28") ~ "Feb 25",
                            due  >=  lubridate::ymd("2025-3-01") & due <=           lubridate::ymd("2025-3-31") ~ "Mar 25",
                            due  >=  lubridate::ymd("2025-4-01") & due <=           lubridate::ymd("2025-4-30") ~ "Apr 25",
                            due  >=  lubridate::ymd("2025-5-01") & due <=           lubridate::ymd("2025-5-31") ~ "May 25",
                            due  >=  lubridate::ymd("2025-6-01") & due <=           lubridate::ymd("2025-6-30") ~ "Jun 25",
                            due  >=  lubridate::ymd("2025-7-01") & due <=           lubridate::ymd("2025-7-31") ~ "Jul 25",
                            TRUE ~ NA_character_)) 

View(freshbymonth)
```

```{r}
fbm_sum <- freshbymonth |>
    count(monfrsh) |>
  mutate(month_year = my(monfrsh)) |>
  arrange(month_year) |>
  select(-month_year)

fbm_sum
```
